description = "Farm 6 Media is a web development company."
features = ["bootstrap", "responsive"]
homepage = "https://farm6media.com"
license = "Copyright 2020"
licenselink = "https://farm6media.com"
min_version = "0.666.0"
name = "Farm 6"
tags = ["landing-page", "google-analytics", "fast", "modern", "minimal", "minimalistic", "business", "agency-template", "themefisher", "hugo-theme", "hugo-templates", "bootstrap", "blog", "responsive", "portfolio", "single-page", "dark", "clean", "simple", "company", "creative", "contact-form", "custom-themes", "mobile", "graphics", "graphic design"]
[author]
homepage = "https://farm6media.com"
name = "Farm 6 Media"
